package jobpostings

import (
	"context"
	"sync"
)

// GetAllJobPostings finds all of the JobPostings using every source.
func GetAllJobPostings(ctx context.Context) <-chan *JobPosting {
	// cat *.go | grep "\bGet" | grep "ctx" | awk '{print $2}' | awk -F '(' '{print $1","}' | grep "Get" | grep -v "GetAllJob" | pbcopy
	all := []func(ctx context.Context) (<-chan *JobPosting, error){
		Get0xJobPostings,
		Get21stCenturyFoxJobPostings,
		Get3MJobPostings,
		GetAdjustJobPostings,
		GetAdobeJobPostings,
		GetAESJobPostings,
		GetAirMapJobPostings,
		GetAirbnbJobPostings,
		GetAirtameJobPostings,
		GetAlterianJobPostings,
		GetAltoJobPostings,
		GetAmazeeJobPostings,
		GetAnchorageJobPostings,
		GetApptioJobPostings,
		GetAzerionJobPostings,
		GetBeamlyJobPostings,
		GetBetterLessonJobPostings,
		GetBetterUpJobPostings,
		GetBishopFoxJobPostings,
		GetBittrexJobPostings,
		GetBlackfynnJobPostings,
		GetBombasJobPostings,
		GetBoseJobPostings,
		GetBraintreeJobPostings,
		GetBrightBytesJobPostings,
		GetBritecoreJobPostings,
		GetBuildiumJobPostings,
		GetBuzzFeedJobPostings,
		GetCAEJobPostings,
		GetCanonicalJobPostings,
		GetCarbonBlackJobPostings,
		GetCarousellJobPostings,
		GetCasperJobPostings,
		GetCatalyticJobPostings,
		GetCBInsightsJobPostings,
		GetCheddarJobPostings,
		GetChewyJobPostings,
		GetChimpJobPostings,
		GetCiscoMerakiJobPostings,
		GetCityAndCountyOfDenverJobPostings,
		GetCloudBeesJobPostings,
		GetCloudflareJobPostings,
		GetCloudreachJobPostings,
		GetCockroachLabsJobPostings,
		GetCodecademyJobPostings,
		GetCoinbaseJobPostings,
		GetColossalJobPostings,
		GetCompassJobPostings,
		GetConductorTechnologiesJobPostings,
		GetCornellUniversityJobPostings,
		GetCoreScientificJobPostings,
		GetCorelightJobPostings,
		GetCuralateJobPostings,
		GetDaticaJobPostings,
		GetDattoJobPostings,
		GetDellJobPostings,
		GetDigitalOceanJobPostings,
		GetDnBJobPostings,
		GetDockerJobPostings,
		GetDotsJobPostings,
		GetDropJobPostings,
		GetDuoSecurityJobPostings,
		GetEarlyWarningJobPostings,
		GetElasticJobPostings,
		GetEpicGamesJobPostings,
		GetERMJobPostings,
		GetEvercommerceJobPostings,
		GetEvernoteJobPostings,
		GetExpediaJobPostings,
		GetExpensifyJobPostings,
		GetFarmersBusinessNetworkJobPostings,
		GetFastlyJobPostings,
		GetFetchRevJobPostings,
		GetFICOJobPostings,
		GetFingerFoodStudiosJobPostings,
		GetFirstJobPostings,
		GetGameChangerJobPostings,
		GetGatesFoundationJobPostings,
		GetGitHubJobPostings,
		GetGitLabJobPostings,
		GetGizmodoJobPostings,
		GetGlowJobPostings,
		GetGoDaddyJobPostings,
		GetGovPredictJobPostings,
		GetGradientJobPostings,
		GetGradleJobPostings,
		GetGrammarlyJobPostings,
		GetGreenpeaceJobPostings,
		GetGridspaceJobPostings,
		GetGustoJobPostings,
		GetHashiCorpJobPostings,
		GetHelloAlfredJobPostings,
		GetHelloFreshJobPostings,
		GetHifyreJobPostings,
		GetHopsyJobPostings,
		GetImageworksJobPostings,
		GetInputJobPostings,
		GetInstabaseJobPostings,
		GetInstacartJobPostings,
		GetInventablesJobPostings,
		GetInvitaeJobPostings,
		GetIOTAJobPostings,
		GetJDAJobPostings,
		GetJetJobPostings,
		GetJoorJobPostings,
		GetJourneraJobPostings,
		GetKantarJobPostings,
		GetKayakJobPostings,
		GetKikJobPostings,
		GetKinnekJobPostings,
		GetLightStepJobPostings,
		GetLighthouseStudiosJobPostings,
		GetLimeadeJobPostings,
		GetLiveNationJobPostings,
		GetLogitechJobPostings,
		GetLyftJobPostings,
		GetLyricJobPostings,
		GetMagicLeapJobPostings,
		GetMajorLeagueBaseballPostings,
		GetMapboxJobPostings,
		GetMastercardJobPostings,
		GetMavenClinicJobPostings,
		GetMavensJobPostings,
		GetMeasurablJobPostings,
		GetMessageBirdJobPostings,
		GetMetalToadJobPostings,
		GetMightyNetworksJobPostings,
		GetModernizeJobPostings,
		GetModsyJobPostings,
		GetMongoDBJobPostings,
		GetMovableInkJobPostings,
		GetNarvarJobPostings,
		GetNationwideJobPostings,
		GetNetlifyJobPostings,
		GetNewEngenJobPostings,
		GetNewYorkTimesJobPostings,
		GetNexientJobPostings,
		GetNextdoorJobPostings,
		GetNS1JobPostings,
		GetNvidiaJobPostings,
		GetOktaJobPostings,
		GetOmadaHealthJobPostings,
		GetOmazeJobPostings,
		GetOneLoginJobPostings,
		GetOpenCosmosJobPostings,
		GetOpenFinJobPostings,
		GetPAEJobPostings,
		GetPalantirJobPostings,
		GetPaloAltoNetworksJobPostings,
		GetPathAIJobPostings,
		GetPathlightJobPostings,
		GetPatreonJobPostings,
		GetPAXJobPostings,
		GetPfizerJobPostings,
		GetPinterestJobPostings,
		GetPioneerSquareLabsJobPostings,
		GetPlatformshJobPostings,
		GetPolicygeniusJobPostings,
		GetPostmatesJobPostings,
		GetPredictiveIndexJobPostings,
		GetProcoreJobPostings,
		GetPsiKickJobPostings,
		GetPushpayJobPostings,
		GetQualtricsJobPostings,
		GetQualysJobPostings,
		GetRapid7JobPostings,
		GetRedditJobPostings,
		GetRelayrJobPostings,
		GetRemarkablyJobPostings,
		GetRemitlyJobPostings,
		GetRiotGamesJobPostings,
		GetRobinhoodJobPostings,
		GetRollPayJobPostings,
		GetRollsRoyceJobPostings,
		GetRubrikJobPostings,
		GetSalesforceJobPostings,
		GetSaltStackJobPostings,
		GetSamsaraJobPostings,
		GetSamsungJobPostings,
		GetSauceLabsJobPostings,
		GetScanditJobPostings,
		GetScreenCloudJobPostings,
		GetSecurityTrailsJobPostings,
		GetSecuronixJobPostings,
		GetSentryJobPostings,
		GetShapeScaleCraterJobPostings,
		GetShoesJobPostings,
		GetSiftJobPostings,
		GetSimpliSafeJobPostings,
		GetSmartsheetJobPostings,
		GetSnapRaiseJobPostings,
		GetSpaceflightIndustriesJobPostings,
		GetSpaceXJobPostings,
		GetSpotHeroJobPostings,
		GetSpotifyJobPostings,
		GetSproutSocialobPostings,
		GetSquarespaceJobPostings,
		GetStateStreetJobPostings,
		GetStauerJobPostings,
		GetStravaJobPostings,
		GetStripeJobPostings,
		GetSumoLogicJobPostings,
		GetSurveyGizmoJobPostings,
		GetSurveyMonkeyJobPostings,
		GetSwatJobPostings,
		GetSymantecJobPostings,
		GetSysdigJobPostings,
		GetT1CGJobPostings,
		GetTableauJobPostings,
		GetTablexiJobPostings,
		GetTacoBellJobPostings,
		GetTalaJobPostings,
		GetTelariaJobPostings,
		GetTheTradeDeskJobPostings,
		GetTiltingPointJobPostings,
		GetTimeIncJobPostings,
		GetToptalJobPostings,
		GetTrilogyEducationJobPostings,
		GetTripAdvisorJobPostings,
		GetTTTStudiosJobPostings,
		GetTutelaJobPostings,
		GetTwilioJobPostings,
		GetUberJobPostings,
		GetUberEtherJobPostings,
		GetUdacityJobPostings,
		GetUniregistryJobPostings,
		GetUnisysJobPostings,
		GetUnity3DJobPostings,
		GetUpstartJobPostings,
		GetVenafiJobPostings,
		GetVenmoJobPostings,
		GetVerifoneJobPostings,
		GetVerishopJobPostings,
		GetVeritasJobPostings,
		GetVerizonMediaJobPostings,
		GetVewdJobPostings,
		GetViceJobPostings,
		GetVoxMediaJobPostings,
		GetVoxterJobPostings,
		GetWeb3JobPostings,
		GetWGamesJobPostings,
		GetWhisperJobPostings,
		GetWholeFoodsJobPostings,
		GetWizelineJobPostings,
		GetXylemJobPostings,
		GetZenefitsJobPostings,
		GetZeroCraterJobPostings,
		GetZeroFoxJobPostings,
		GetZipwhipJobPostings,
		GetZumeJobPostings,
		GetZyrisJobPostings,
	}

	allJobPostings := make(chan *JobPosting)

	go func() {
		defer close(allJobPostings)

		wg := sync.WaitGroup{}

		for _, jobPostingSource := range all {
			jobPostingChannel, err := jobPostingSource(ctx)

			if err == nil {
				wg.Add(1)
				go func() {
					defer wg.Done()
					for singlePosting := range jobPostingChannel {
						select {
						case allJobPostings <- singlePosting:
						case <-ctx.Done():
							return
						}
					}
				}()
			}
		}

		wg.Wait()
	}()

	return allJobPostings
}
